### ISSUE TITLE
debian编译不了

### ISSUE THREAD

**Issue by Saturday-morning** [CGLemon/Sayuri#3]
我是Debian11，这是  执行 make 的时候的报错：
<pre>In file included from <b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:1</b>:
<b>/home/suerya/工程/Sayuri/src/pattern/pattern.h:14:13:</b> <font color="#C01C28"><b>error: </b></font>‘<b>uint64_t</b>’ in namespace ‘<b>std</b>’ does not name a type
   14 | extern std::<font color="#C01C28"><b>uint64_t</b></font> PatternHash[8][4][kMaxPatternArea];
      |             <font color="#C01C28"><b>^~~~~~~~</b></font>
In file included from <b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:2</b>:
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:9:26:</b> <font color="#C01C28"><b>error: </b></font>‘<b>std::string</b>’ has not been declared
    9 |     void Initialize(std::<font color="#C01C28"><b>string</b></font> filename);
      |                          <font color="#C01C28"><b>^~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:11:28:</b> <font color="#C01C28"><b>error: </b></font>‘<b>std::uint64_t</b>’ has not been declared
   11 |     bool ProbePattern(std::<font color="#C01C28"><b>uint64_t</b></font> hash, float &amp;val) const;
      |                            <font color="#C01C28"><b>^~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:12:28:</b> <font color="#C01C28"><b>error: </b></font>‘<b>std::uint64_t</b>’ has not been declared
   12 |     bool ProbeFeature(std::<font color="#C01C28"><b>uint64_t</b></font> hash, float &amp;val) const;
      |                            <font color="#C01C28"><b>^~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:15:29:</b> <font color="#C01C28"><b>error: </b></font>‘<b>std::uint64_t</b>’ has not been declared
   15 |     bool InsertPattern(std::<font color="#C01C28"><b>uint64_t</b></font> hash, float val);
      |                             <font color="#C01C28"><b>^~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:16:29:</b> <font color="#C01C28"><b>error: </b></font>‘<b>std::uint64_t</b>’ has not been declared
   16 |     bool InsertFeature(std::<font color="#C01C28"><b>uint64_t</b></font> hash, float val);
      |                             <font color="#C01C28"><b>^~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:18:29:</b> <font color="#C01C28"><b>error: </b></font>‘<b>uint64_t</b>’ is not a member of ‘<b>std</b>’
   18 |     std::unordered_map&lt;std::<font color="#C01C28"><b>uint64_t</b></font>, float&gt; pattern_dict_;
      |                             <font color="#C01C28"><b>^~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:18:29:</b> <font color="#C01C28"><b>error: </b></font>‘<b>uint64_t</b>’ is not a member of ‘<b>std</b>’
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:18:44:</b> <font color="#C01C28"><b>error: </b></font>template argument 1 is invalid
   18 |     std::unordered_map&lt;std::uint64_t, float<font color="#C01C28"><b>&gt;</b></font> pattern_dict_;
      |                                            <font color="#C01C28"><b>^</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:18:44:</b> <font color="#C01C28"><b>error: </b></font>template argument 3 is invalid
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:18:44:</b> <font color="#C01C28"><b>error: </b></font>template argument 4 is invalid
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:18:44:</b> <font color="#C01C28"><b>error: </b></font>template argument 5 is invalid
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:19:29:</b> <font color="#C01C28"><b>error: </b></font>‘<b>uint64_t</b>’ is not a member of ‘<b>std</b>’
   19 |     std::unordered_map&lt;std::<font color="#C01C28"><b>uint64_t</b></font>, float&gt; feature_dict_;
      |                             <font color="#C01C28"><b>^~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:19:29:</b> <font color="#C01C28"><b>error: </b></font>‘<b>uint64_t</b>’ is not a member of ‘<b>std</b>’
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:19:44:</b> <font color="#C01C28"><b>error: </b></font>template argument 1 is invalid
   19 |     std::unordered_map&lt;std::uint64_t, float<font color="#C01C28"><b>&gt;</b></font> feature_dict_;
      |                                            <font color="#C01C28"><b>^</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:19:44:</b> <font color="#C01C28"><b>error: </b></font>template argument 3 is invalid
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:19:44:</b> <font color="#C01C28"><b>error: </b></font>template argument 4 is invalid
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:19:44:</b> <font color="#C01C28"><b>error: </b></font>template argument 5 is invalid
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:15:6:</b> <font color="#C01C28"><b>error: </b></font>no declaration matches ‘<b>void GammasDict::Initialize(std::string)</b>’
   15 | void <font color="#C01C28"><b>GammasDict</b></font>::Initialize(std::string filename) {
      |      <font color="#C01C28"><b>^~~~~~~~~~</b></font>
In file included from <b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:2</b>:
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:9:10:</b> <font color="#2AA1B3"><b>note: </b></font>candidate is: ‘<b>void GammasDict::Initialize(int)</b>’
    9 |     void <font color="#2AA1B3"><b>Initialize</b></font>(std::string filename);
      |          <font color="#2AA1B3"><b>^~~~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:5:7:</b> <font color="#2AA1B3"><b>note: </b></font>‘<b>class GammasDict</b>’ defined here
    5 | class <font color="#2AA1B3"><b>GammasDict</b></font> {
      |       <font color="#2AA1B3"><b>^~~~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:73:6:</b> <font color="#C01C28"><b>error: </b></font>no declaration matches ‘<b>bool GammasDict::ProbePattern(uint64_t, float&amp;) const</b>’
   73 | bool <font color="#C01C28"><b>GammasDict</b></font>::ProbePattern(std::uint64_t hash, float &amp;val) const {
      |      <font color="#C01C28"><b>^~~~~~~~~~</b></font>
In file included from <b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:2</b>:
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:11:10:</b> <font color="#2AA1B3"><b>note: </b></font>candidate is: ‘<b>bool GammasDict::ProbePattern(int, float&amp;) const</b>’
   11 |     bool <font color="#2AA1B3"><b>ProbePattern</b></font>(std::uint64_t hash, float &amp;val) const;
      |          <font color="#2AA1B3"><b>^~~~~~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:5:7:</b> <font color="#2AA1B3"><b>note: </b></font>‘<b>class GammasDict</b>’ defined here
    5 | class <font color="#2AA1B3"><b>GammasDict</b></font> {
      |       <font color="#2AA1B3"><b>^~~~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:82:6:</b> <font color="#C01C28"><b>error: </b></font>no declaration matches ‘<b>bool GammasDict::ProbeFeature(uint64_t, float&amp;) const</b>’
   82 | bool <font color="#C01C28"><b>GammasDict</b></font>::ProbeFeature(std::uint64_t hash, float &amp;val) const {
      |      <font color="#C01C28"><b>^~~~~~~~~~</b></font>
In file included from <b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:2</b>:
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:12:10:</b> <font color="#2AA1B3"><b>note: </b></font>candidate is: ‘<b>bool GammasDict::ProbeFeature(int, float&amp;) const</b>’
   12 |     bool <font color="#2AA1B3"><b>ProbeFeature</b></font>(std::uint64_t hash, float &amp;val) const;
      |          <font color="#2AA1B3"><b>^~~~~~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:5:7:</b> <font color="#2AA1B3"><b>note: </b></font>‘<b>class GammasDict</b>’ defined here
    5 | class <font color="#2AA1B3"><b>GammasDict</b></font> {
      |       <font color="#2AA1B3"><b>^~~~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:91:6:</b> <font color="#C01C28"><b>error: </b></font>no declaration matches ‘<b>bool GammasDict::InsertPattern(uint64_t, float)</b>’
   91 | bool <font color="#C01C28"><b>GammasDict</b></font>::InsertPattern(std::uint64_t hash, float val) {
      |      <font color="#C01C28"><b>^~~~~~~~~~</b></font>
In file included from <b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:2</b>:
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:15:10:</b> <font color="#2AA1B3"><b>note: </b></font>candidate is: ‘<b>bool GammasDict::InsertPattern(int, float)</b>’
   15 |     bool <font color="#2AA1B3"><b>InsertPattern</b></font>(std::uint64_t hash, float val);
      |          <font color="#2AA1B3"><b>^~~~~~~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:5:7:</b> <font color="#2AA1B3"><b>note: </b></font>‘<b>class GammasDict</b>’ defined here
    5 | class <font color="#2AA1B3"><b>GammasDict</b></font> {
      |       <font color="#2AA1B3"><b>^~~~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:100:6:</b> <font color="#C01C28"><b>error: </b></font>no declaration matches ‘<b>bool GammasDict::InsertFeature(uint64_t, float)</b>’
  100 | bool <font color="#C01C28"><b>GammasDict</b></font>::InsertFeature(std::uint64_t hash, float val) {
      |      <font color="#C01C28"><b>^~~~~~~~~~</b></font>
In file included from <b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:2</b>:
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:16:10:</b> <font color="#2AA1B3"><b>note: </b></font>candidate is: ‘<b>bool GammasDict::InsertFeature(int, float)</b>’
   16 |     bool <font color="#2AA1B3"><b>InsertFeature</b></font>(std::uint64_t hash, float val);
      |          <font color="#2AA1B3"><b>^~~~~~~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.h:5:7:</b> <font color="#2AA1B3"><b>note: </b></font>‘<b>class GammasDict</b>’ defined here
    5 | class <font color="#2AA1B3"><b>GammasDict</b></font> {
</pre>
是这个系统不满足什么需求吗？debian和ubuntu之间的什么差距才会导致这个问题发生呢？

**Comment by CGLemon** [comment]
不好意思，這是我的問題，由於少了一些 header file  ，導致不同版本的 gcc 可能編譯不過。請在 ```src/pattern/gammas_dict.h``` 檔案中加入以下的 header file

```
#pragma once

#include <unordered_map>
#include <string>  // 加入的 header file
#include <cstdint> // 加入的 header file

class GammasDict {
    ......
};
```
如果成功編譯或是有其它問題的話，請通知我，謝謝！

**Comment by Saturday-morning** [comment]
非常感谢你的答复！
现在变成了这样：
<pre>In file included from <b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:1</b>:
<b>/home/suerya/工程/Sayuri/src/pattern/pattern.h:14:13:</b> <font color="#C01C28"><b>error: </b></font>‘<b>uint64_t</b>’ in namespace ‘<b>std</b>’ does not name a type
   14 | extern std::<font color="#C01C28"><b>uint64_t</b></font> PatternHash[8][4][kMaxPatternArea];
      |             <font color="#C01C28"><b>^~~~~~~~</b></font>
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:</b> In member function ‘<b>void GammasDict::Initialize(std::string)</b>’:
<b>/home/suerya/工程/Sayuri/src/pattern/gammas_dict.cc:59:38:</b> <font color="#C01C28"><b>error: </b></font>‘<b>PatternHash</b>’ was not declared in this scope
   59 |                 std::uint64_t hash = <font color="#C01C28"><b>PatternHash</b></font>[0][kInvalid][0];
      |                                      <font color="#C01C28"><b>^~~~~~~~~~~</b></font>
make[2]: *** [CMakeFiles/Sayuri.dir/build.make:290：CMakeFiles/Sayuri.dir/src/pattern/gammas_dict.cc.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:95：CMakeFiles/Sayuri.dir/all] 错误 2
make: *** [Makefile:103：all] 错误 2
</pre>

**Comment by CGLemon** [comment]
請在 ```src/pattern/pattern.h``` 檔案中加入以下的 header file

```
#pragma once

#include <array>
#include <cstdint> // 加入的 header file

void PatternHashAndCoordsInit();
int CharToColor(char s);

static constexpr int kMaxPatternDist = 10;
static constexpr int kMaxPatternArea = kMaxPatternDist * kMaxPatternDist;

struct PtCoord { int x, y; };
extern std::array<PtCoord, kMaxPatternArea> kPointCoords;
extern std::array<int, kMaxPatternDist + 2> kPointIndex;
extern std::uint64_t PatternHash[8][4][kMaxPatternArea];
```

**Comment by Saturday-morning** [comment]
编译成功了！！congratulation！

**Comment by CGLemon** [comment]
感謝你的幫助！晚點我會推送修正過的版本
